"use client";

import { useEffect, useState, useRef, useMemo } from "react";
import { SectionWrapper } from "@/components/ui/section-wrapper";
import { SectionHeading } from "@/components/ui/section-heading";

const S = (value: number, suffix: string, label: string, prefix?: string) =>
  prefix ? { value, suffix, label, prefix } : { value, suffix, label };

const CHRIS_STATS = [
  // ====== TIER 1: THE REAL ONES (1-32) ======
  S(12, "+", "Years Leading Nonprofits"),
  S(30, "+", "Organizations Served"),
  S(145, "", "Residents Stabilized"),
  S(52, "", "Children Housed"),
  S(500, "K+", "Acute-Care Costs Avoided", "$"),
  S(96, "%", "Client Retention Rate"),
  S(1200, "+", "Lives Directly Impacted"),
  S(2, "M+", "Client Budgets Managed", "$"),
  S(85, "+", "SOPs Delivered"),
  S(60, "+", "Workflows Redesigned"),
  S(35, "+", "Training Programs Built"),
  S(100, "+", "Process Docs Created"),
  S(45, "+", "Systems Implemented"),
  S(15, "+", "Dashboards Created"),
  S(25, "+", "Board Presentations"),
  S(18, "", "Strategic Plans Written"),
  S(40, "%", "Faster Staff Onboarding"),
  S(3, "x", "Efficiency Gains"),
  S(50, "%", "Less Staff Turnover"),
  S(70, "%", "Faster Decisions"),
  S(90, "%", "On-Time Delivery"),
  S(100, "%", "On Budget"),
  S(4, ".9/5", "Satisfaction Score"),
  S(48, "hr", "Fastest Diagnostic"),
  S(99, "%", "Email Response Rate"),
  S(8, "", "Industry Sectors"),
  S(5, "", "States Operated In"),
  S(200, "+", "Stakeholder Meetings"),
  S(300, "+", "Action Items Completed"),
  S(75, "+", "Team Retreats Facilitated"),
  S(40, "+", "Grant Reports Streamlined"),
  S(22, "", "Org Charts Untangled"),

  // ====== TIER 2: SLIGHTLY SILLY (33-96) ======
  S(10000, "+", "Cups of Coffee"),
  S(347, "", "Whiteboards Filled"),
  S(0, "", "Jargon Decks Delivered"),
  S(1, "", "Mission: Yours"),
  S(42, "", "Meaning of Life (Confirmed)"),
  S(0, "", "Times He Said 'Synergy'"),
  S(2847, "", "Post-It Notes Used"),
  S(100, "%", "Cares About Your Mission"),
  S(14, "", "Pens Borrowed, Never Returned"),
  S(1, "", "Nonprofit Whisperer"),
  S(365, "", "Days/Year Thinking About SOPs"),
  S(0, "", "Nonsense Tolerated"),
  S(7, "am", "Earliest Meeting Survived"),
  S(412, "", "Spreadsheet Tabs Open"),
  S(3, "", "Monitor Setup (Minimum)"),
  S(99, "%", "Operational Gravity"),
  S(0, "", "Days Off (Mentally)"),
  S(1, "", "Guy Who Reads the SOP"),
  S(500, "+", "Dad Jokes Per Quarter"),
  S(100, "%", "That Guy Energy"),
  S(12, "", "Highlighter Colors Owned"),
  S(0, "", "Meetings That Should've Been Emails"),
  S(1, "", "Legendary Handshake"),
  S(88, "mph", "Speed of Operational Fix"),
  S(24, "/7", "Availability (In Spirit)"),
  S(9001, "", "Power Level"),
  S(47, "", "Motivational Speeches"),
  S(0, "", "Times He Lost His Cool"),
  S(312, "", "LinkedIn Endorsements"),
  S(6, "", "Fonts He Approves Of"),
  S(100, "%", "Firm Handshake Rating"),
  S(4, "", "Ties Owned (All Navy)"),
  S(742, "", "Google Docs Created"),
  S(11, "", "Standing Desk Adjustments/Day"),
  S(0, "", "Printer Jams Caused"),
  S(1, "", "Favorite Mug"),
  S(3500, "+", "Emails Sent This Year"),
  S(0, "", "Emails Ignored"),
  S(284, "", "Calendar Invites Sent"),
  S(0, "", "Meetings Without Agenda"),
  S(156, "", "Leadership Books on Shelf"),
  S(8, "", "Books Actually Finished"),
  S(2, "", "Podcast Appearances"),
  S(1, "", "TED Talk Idea (In Progress)"),
  S(0, "", "Fear of Spreadsheets"),
  S(99, "%", "Belief in Your Nonprofit"),
  S(1, "", "Lucky Pen"),
  S(0, "", "Tolerance for BS"),
  S(100, "%", "Good Vibes Only"),
  S(0, "", "Times He Ghosted a Client"),
  S(17, "", "Plants on His Desk"),
  S(5, "/5", "Stars (If Restaurant)"),
  S(87, "%", "Chance of High-Five"),
  S(1, "", "Golden Retriever Energy"),
  S(0, "", "Enemies (Known)"),
  S(999, "+", "Reasons to Hire Chris"),
  S(52, "", "Weeks/Year in Khakis"),
  S(3, "", "Backup Phone Chargers"),
  S(0, "", "Times He Said 'Circle Back'"),
  S(0, "", "Times He Said 'Low-Hanging Fruit'"),

  // ====== TIER 3: FULLY UNHINGED (97-200) ======
  S(1, "", "Go-To Karaoke Song"),
  S(100, "%", "Would Recommend to Friend"),
  S(0, "", "Regrets"),
  S(1, "", "Absolute Legend"),
  S(69, "", "Nice"),
  S(420, "", "Also Nice"),
  S(1, "", "GOAT"),
  S(4, "", "Coffees Before 9am"),
  S(0, "", "Decaf (Never)"),
  S(312, "", "Granola Bars at Desk"),
  S(1, "", "Lunch Order (Always Same)"),
  S(52, "", "Friday Donuts for Team"),
  S(0, "", "Casual Fridays Skipped"),
  S(1, "", "Signature Look"),
  S(3, "", "Identical Shoe Pairs"),
  S(100, "%", "Tucked-In Shirt Rate"),
  S(1, "", "Watch (Casio, Obviously)"),
  S(47000, "mi", "Driven for Meetings"),
  S(0, "", "Road Rage Incidents"),
  S(100, "%", "Seatbelt Usage"),
  S(4, "", "Passwords He Remembers"),
  S(0, "", "Crypto Investments"),
  S(47, "", "Apps on Phone"),
  S(3, "", "Apps Actually Used"),
  S(0, "", "TikToks Made"),
  S(1, "", "LinkedIn Thought Leader"),
  S(0, "", "NFTs Purchased"),
  S(1, "x/wk", "Gym (Actual)"),
  S(0, "", "Marathons Finished"),
  S(1, "", "5K (Walked Most of It)"),
  S(8000, "", "Steps/Day (Good Day)"),
  S(5000, "+", "Total Meetings Attended"),
  S(47, "", "Meetings Where He Doodled"),
  S(0, "", "Meetings He Slept Through"),
  S(312, "", "Times He Said 'Great Question'"),
  S(15, "min", "Avg Early to Meetings"),
  S(100, "%", "Empathy"),
  S(0, "", "Voice Raised Count"),
  S(500, "+", "Pep Talks Given"),
  S(1, "", "Team Cry (It Was Beautiful)"),
  S(0, "", "Grudges Held"),
  S(100, "%", "Emotional Intelligence"),
  S(0, "", "Passive-Aggressive Emails"),
  S(847, "", "Footnotes Written"),
  S(0, "", "Docs Without Headers"),
  S(100, "%", "Table of Contents Rate"),
  S(12, "pt", "Only Acceptable Font Size"),
  S(0, "", "Comic Sans Usage"),
  S(47, "", "Templates Created"),
  S(1, "", "Spirit Animal (Eagle)"),
  S(100, "%", "Dog Person"),
  S(0, "", "Cat Person (Sorry)"),
  S(3, "", "Office Fish (Named)"),
  S(1, "", "Desk Plant Named Gerald"),
  S(100, "%", "Would Pet Every Dog"),
  S(72, "°F", "Ideal Thermostat"),
  S(0, "", "Thermostat Wars Lost"),
  S(100, "%", "Umbrella Preparedness"),
  S(1, "", "Favorite Season (Fall)"),
  S(1, "", "Spotify Playlist (Focus Mode)"),
  S(1, "", "NPR Tote Bag"),
  S(6, "hr", "Avg Sleep (Weeknight)"),
  S(5, "am", "Alarm Setting"),
  S(0, "", "Snooze Button Usage"),
  S(3, "", "Dreams About Org Charts"),
  S(0, "", "Voicemails Unreturned"),
  S(0, "", "Accidental Reply-Alls"),
  S(47, "", "Thank You Cards Sent"),
  S(100, "%", "Professional Yet Warm"),
  S(100, "%", "X-Ray Vision for Dysfunction"),
  S(1, "", "Superpower (Clarity)"),
  S(0, "", "Kryptonite (None Found)"),
  S(100, "%", "Heroic"),

  // ====== TIER 4: GETTING WEIRD (201-350) ======
  S(0, "", "Holiday Parties Missed"),
  S(1, "", "Secret Santa MVP"),
  S(12, "", "Ugly Sweaters Owned"),
  S(1, "", "Potluck Dish (Legendary Chili)"),
  S(50, "", "States Visited"),
  S(0, "", "Countries Banned From"),
  S(1, "", "Employee of Month (Self)"),
  S(12, "", "Months in a Row"),
  S(3, "", "Recipes He Knows"),
  S(1, "", "Signature Dish (Pasta)"),
  S(0, "", "Kitchen Fires"),
  S(100, "%", "Grill Confidence"),
  S(5, "", "Hot Sauce Bottles"),
  S(1, "", "Purpose in Life (Found)"),
  S(0, "", "Existential Crises at Work"),
  S(0, "", "Online Arguments"),
  S(100, "%", "Integrity"),
  S(100, "%", "Work Ethic"),
  S(100, "%", "Reliability"),
  S(100, "%", "Trustworthiness"),
  S(100, "%", "Dedication"),
  S(100, "%", "Authenticity"),
  S(100, "%", "Compassion"),
  S(100, "%", "Focus"),
  S(100, "%", "Replaces the TP Roll"),
  S(0, "", "Kitchen Sink Dishes Left"),
  S(0, "", "HR Complaints Filed"),
  S(9999, "", "HP"),
  S(100, "", "Charisma"),
  S(0, "", "Weaknesses Found"),
  S(0, "", "Chance We're Deleting This"),
  S(10, "/10", "Would Operate Again"),
  // New stuff starts here
  S(1, "", "Man Who Shows Up"),
  S(0, "", "Ghosted Zoom Calls"),
  S(247, "", "Motivational Quotes Bookmarked"),
  S(0, "", "Times He Wore Crocs to Work"),
  S(1, "", "Iron Will"),
  S(0, "", "Panic Attacks During Audits"),
  S(100, "%", "Calm Under Pressure"),
  S(8, "", "Tabs Open in Incognito (SOP Research)"),
  S(0, "", "Times He Missed a Deadline"),
  S(1, "", "Guy Your Org Needs"),
  S(37, "", "Neckties Donated to Goodwill"),
  S(0, "", "Times He Used 'Per My Last Email'"),
  S(1, "", "Walking Org Chart"),
  S(100, "%", "Follows Through"),
  S(0, "", "Empty Promises"),
  S(3, "", "Times He Fixed the Wi-Fi"),
  S(1, "", "Office IT Guy (Backup)"),
  S(0, "", "Times He Blamed the Intern"),
  S(100, "%", "Takes Responsibility"),
  S(14, "", "Emergency Pens in Desk"),
  S(0, "", "Times He Took the Last Coffee"),
  S(1, "", "Always Makes a Fresh Pot"),
  S(0, "", "Gossip Participated In"),
  S(100, "%", "Discretion"),
  S(77, "", "Times He Held the Elevator"),
  S(0, "", "Times He Let It Close"),
  S(1, "", "Elevator Gentleman"),
  S(0, "", "Parking Spots Stolen"),
  S(100, "%", "Parking Karma"),
  S(23, "", "Times He Let Someone Merge"),
  S(0, "", "Honks Given in Anger"),
  S(1, "", "Zen Driver"),
  S(0, "", "Microwaved Fish at Work"),
  S(100, "%", "Microwave Etiquette"),
  S(0, "", "Left Dishes in Sink"),
  S(1, "", "Washes His Own Mug"),
  S(0, "", "Office Fridge Theft"),
  S(100, "%", "Fridge Honor System"),
  S(0, "", "Reply-All Catastrophes"),
  S(100, "%", "Email Etiquette"),
  S(0, "", "Used Comic Sans in a Deck"),
  S(100, "%", "Typography Standards"),
  S(0, "", "Clipart in Presentations"),
  S(100, "%", "Visual Taste"),
  S(1, "", "PowerPoint Artisan"),
  S(0, "", "Slide Decks Over 50 Slides"),
  S(100, "%", "Brevity"),
  S(0, "", "Unnecessary Pie Charts"),
  S(100, "%", "Data Integrity"),
  S(1, "", "Chart Whisperer"),
  S(0, "", "Used 3D Bar Charts (Never)"),
  S(100, "%", "Flat Design Advocate"),

  // ====== TIER 5: WHY ARE WE STILL HERE (351-500) ======
  S(0, "", "Times He Said 'Move the Needle'"),
  S(0, "", "Times He Said 'Boil the Ocean'"),
  S(0, "", "Times He Said 'Drill Down'"),
  S(0, "", "Times He Said 'Take Offline'"),
  S(0, "", "Times He Said 'Run It Up the Flagpole'"),
  S(0, "", "Times He Said 'Bandwidth'"),
  S(0, "", "Times He Said 'Touch Base'"),
  S(0, "", "Corporate Buzzwords Used (Total)"),
  S(100, "%", "Plain English Speaker"),
  S(1, "", "Anti-Jargon Warrior"),
  S(7, "", "Zoom Backgrounds Owned"),
  S(1, "", "Favorite (Bookshelf, Obviously)"),
  S(0, "", "Zoom Calls in Pajamas"),
  S(100, "%", "Camera Always On"),
  S(0, "", "You're on Mute Incidents"),
  S(1, "", "Mute Button Master"),
  S(3, "", "Times He Walked Into Frame"),
  S(0, "", "Inappropriate Screen Shares"),
  S(100, "%", "Screen Share Readiness"),
  S(1, "", "Desktop: Clean"),
  S(0, "", "Desktop Icons (All in Folders)"),
  S(100, "%", "File Organization"),
  S(0, "", "Files Named 'Final_v2_REAL_FINAL'"),
  S(100, "%", "Version Control"),
  S(1, "", "Naming Convention (Sacred)"),
  S(0, "", "Lost Files"),
  S(100, "%", "Backup Discipline"),
  S(3, "", "External Hard Drives"),
  S(1, "", "Cloud Storage Evangelist"),
  S(0, "", "USB Sticks Still in Use"),
  S(14, "", "Bookmarks Folders"),
  S(0, "", "Bookmarks That Don't Work"),
  S(100, "%", "Bookmark Maintenance"),
  S(0, "", "Saved Passwords in Browser"),
  S(1, "", "Password Hygiene A+"),
  S(0, "", "Times He Used 'password123'"),
  S(100, "%", "Cybersecurity Awareness"),
  S(0, "", "Phishing Emails Clicked"),
  S(47, "", "Phishing Emails Reported"),
  S(1, "", "IT Security Hero"),
  S(0, "", "Viruses Downloaded"),
  S(100, "%", "Antivirus Compliance"),
  S(1, "", "Windows Update: Always Current"),
  S(0, "", "Blue Screens of Death"),
  S(100, "%", "Tech Reliability"),
  S(0, "", "Rage Quits"),
  S(100, "%", "Persistence"),
  S(1, "", "Keeps Going"),
  S(0, "", "Gave Up"),

  // ====== TIER 6: LOSING IT (501-650) ======
  S(1, "", "Has Definitely Googled 'Am I a Good Leader'"),
  S(100, "%", "The Answer Was Yes"),
  S(0, "", "Times Wikipedia Was Wrong About Him"),
  S(1, "", "Should Have a Wikipedia Page"),
  S(0, "", "Nemeses"),
  S(1, "", "Arch-Nemesis (Inefficiency)"),
  S(0, "", "Dramatic Entrances"),
  S(1, "", "Enters Rooms Normally (Respectable)"),
  S(0, "", "Capes Worn to Work"),
  S(1, "", "Cape Energy (Internal)"),
  S(100, "%", "Main Character Energy"),
  S(0, "", "Side Character Moments"),
  S(1, "", "Protagonist"),
  S(0, "", "Plot Holes in His Career"),
  S(100, "%", "Character Arc (Complete)"),
  S(5, "/5", "Rotten Tomatoes Score (Life)"),
  S(98, "%", "Audience Score"),
  S(0, "", "Bad Reviews"),
  S(1, "", "Certified Fresh"),
  S(100, "%", "Would Watch Again"),
  S(0, "", "Sequel Needed (He's Still Going)"),
  S(1, "", "Chris Pearson Cinematic Universe"),
  S(0, "", "Box Office Flops"),
  S(1, "B", "Projected Lifetime Impact", "$"),
  S(0, "", "Times He's Been Wrong"),
  S(1, "", "Time He Was Wrong (Learned From It)"),
  S(100, "%", "Growth Mindset"),
  S(0, "", "Fixed Mindset Moments"),
  S(1, "", "Carol Dweck Would Be Proud"),
  S(100, "%", "Self-Awareness"),
  S(0, "", "Blind Spots"),
  S(1, "", "OK Maybe One Blind Spot (His Own Greatness)"),
  S(0, "", "Times He Bragged"),
  S(500, "", "Stats on Page That Brag For Him"),
  S(1, "", "Delegation King"),
  S(0, "", "Micromanagement Incidents"),
  S(100, "%", "Trusts His Team"),
  S(0, "", "Hover Rate"),
  S(1, "", "Gives Space"),
  S(100, "%", "Respects Boundaries"),
  S(0, "", "Texts After 9pm (Work)"),
  S(1, "", "Work-Life Balance (Aspirational)"),
  S(0, "", "Sunday Scaries Given"),
  S(100, "%", "Monday Motivation"),
  S(0, "", "Hump Day Complaints"),
  S(100, "%", "Friday Energy (Every Day)"),
  S(0, "", "Weekend Work Emails"),
  S(1, "", "OK Fine Maybe One"),
  S(0, "", "Vacation Auto-Replies Ignored"),
  S(100, "%", "Respects PTO"),
  S(0, "", "Called Someone on Vacation"),
  S(100, "%", "Boundary Respect"),
  S(0, "", "Surprise Monday Meetings"),
  S(100, "%", "Calendar Transparency"),
  S(0, "", "Hidden Agendas"),
  S(100, "%", "Agenda Transparency"),
  S(1, "", "What You See Is What You Get"),
  S(0, "", "Fine Print"),
  S(100, "%", "No Hidden Fees"),
  S(0, "", "Upsells"),
  S(1, "", "Honest Pricing"),
  S(0, "", "Bait and Switch"),
  S(100, "%", "Delivers What He Promises"),
  S(0, "", "Broken Promises"),
  S(1, "", "Promise Keeper"),
  S(0, "", "Pinky Promises Broken"),
  S(100, "%", "Pinky Promise Integrity"),
  S(1, "", "Scout's Honor"),
  S(0, "", "Oath Violations"),
  S(100, "%", "Honor"),

  // ====== TIER 7: DESCENT INTO MADNESS (651-800) ======
  S(1, "", "Has Strong Opinions About Staplers"),
  S(0, "", "Stapler Thefts (He's Not Milton)"),
  S(1, "", "Swingline Loyalist"),
  S(0, "", "Paper Clips Used (Staples Only)"),
  S(100, "%", "Pro-Staple"),
  S(0, "", "Binder Clip Incidents"),
  S(47, "", "Rubber Bands in Desk Drawer"),
  S(1, "", "Junk Drawer (Organized)"),
  S(0, "", "Lost Scissors"),
  S(3, "", "Tape Dispensers (All Full)"),
  S(100, "%", "Office Supply Readiness"),
  S(1, "", "Has a Label Maker (Uses It)"),
  S(0, "", "Unlabeled Folders"),
  S(100, "%", "Label Compliance"),
  S(0, "", "Folders Without Tabs"),
  S(100, "%", "Tab Game Strong"),
  S(1, "", "Color-Coded Everything"),
  S(0, "", "Monochrome Filing"),
  S(7, "", "Colors in His Filing System"),
  S(100, "%", "ROY G. BIV Compliance"),
  S(0, "", "Times He Mixed Up Red and Orange Folders"),
  S(100, "%", "Color Accuracy"),
  S(1, "", "Has a Folder for His Folders"),
  S(0, "", "Meta-Filing Errors"),
  S(100, "%", "Recursive Organization"),
  S(1, "", "Would Alphabetize His Spice Rack"),
  S(0, "", "Spices Out of Order"),
  S(100, "%", "Spice Rack Integrity"),
  S(1, "", "Probably Alphabetizes His Socks"),
  S(0, "", "Mismatched Socks (Ever)"),
  S(100, "%", "Sock Game"),
  S(1, "", "Sock Drawer: Immaculate"),
  S(0, "", "Lost Socks"),
  S(100, "%", "Laundry Discipline"),
  S(0, "", "Wrinkled Shirts"),
  S(100, "%", "Iron Man (Literally Irons)"),
  S(1, "", "Ironing Board (Dedicated)"),
  S(0, "", "Dry Cleaning Mishaps"),
  S(100, "%", "Dry Clean Only Compliance"),
  S(1, "", "Knows What 'Dry Clean Only' Means"),
  S(0, "", "Bleach Accidents"),
  S(100, "%", "Laundry Competence"),
  S(1, "", "Separates Whites and Colors"),
  S(0, "", "Pink Shirt Incidents"),
  S(100, "%", "Fabric Respect"),
  S(0, "", "Shrunken Sweaters"),
  S(100, "%", "Read the Care Label"),
  S(1, "", "Yes He Reads Care Labels"),
  S(0, "", "Clothing Casualties"),
  S(100, "%", "Wardrobe Preservation"),
  S(0, "", "Fashion Emergencies"),
  S(1, "", "Always Prepared"),
  S(0, "", "Forgot His Belt"),
  S(100, "%", "Belt Reliability"),
  S(0, "", "Wrong Shoes for Event"),
  S(100, "%", "Shoe Appropriateness"),
  S(1, "", "Owns a Lint Roller"),
  S(100, "%", "Lint-Free"),
  S(0, "", "Cat Hair on Suit"),
  S(100, "%", "Professional Appearance"),
  S(1, "", "Mirror Check Before Meetings"),
  S(0, "", "Spinach in Teeth (Public)"),
  S(100, "%", "Dental Awareness"),
  S(0, "", "Bad Breath Reports"),
  S(100, "%", "Mint Game"),
  S(1, "", "Always Has Gum"),
  S(0, "", "Gum Stuck Under Desk"),
  S(100, "%", "Gum Disposal Ethics"),
  S(0, "", "Littering"),
  S(100, "%", "Recycles"),

  // ====== TIER 8: IS THIS STILL GOING (801-900) ======
  S(1, "", "Can Parallel Park"),
  S(0, "", "Parking Tickets"),
  S(100, "%", "Parallel Parking Success Rate"),
  S(1, "", "Signals Before Turning"),
  S(100, "%", "Turn Signal Usage"),
  S(0, "", "Cut Off Other Drivers"),
  S(1, "", "Lets Pedestrians Cross"),
  S(100, "%", "Crosswalk Respect"),
  S(0, "", "Jaywalking"),
  S(100, "%", "Follows Crosswalk Signals"),
  S(0, "", "Speed Limit Violations"),
  S(100, "%", "Speed Compliance"),
  S(1, "", "Cruise Control User"),
  S(0, "", "Road Trip Bathroom Denials"),
  S(100, "%", "Stops When You Need To"),
  S(1, "", "Perfect Road Trip Companion"),
  S(0, "", "Controls the Aux Cord Aggressively"),
  S(100, "%", "Aux Cord Democracy"),
  S(0, "", "Ate Smelly Food in Car"),
  S(100, "%", "Car Freshness"),
  S(0, "", "Gas Tank Below Quarter"),
  S(100, "%", "Fuel Preparedness"),
  S(1, "", "Full Tank Energy"),
  S(0, "", "Run Out of Gas"),
  S(100, "%", "Planning Ahead"),
  S(1, "", "AAA Member"),
  S(0, "", "AAA Calls Made"),
  S(100, "%", "Vehicle Maintenance"),
  S(0, "", "Check Engine Lights Ignored"),
  S(1, "", "Goes to the Mechanic On Time"),
  S(100, "%", "Oil Change Compliance"),
  S(0, "", "Overdue Oil Changes"),
  S(1, "", "Tire Pressure: Always Checked"),
  S(100, "%", "PSI Awareness"),
  S(0, "", "Flat Tires (Chris's Fault)"),
  S(100, "%", "Spare Tire Readiness"),
  S(1, "", "Knows How to Change a Tire"),
  S(0, "", "Called Dad to Change Tire"),
  S(100, "%", "Self-Sufficiency"),
  S(1, "", "Swiss Army Knife (In Car)"),
  S(0, "", "Emergency Kit Missing Items"),
  S(100, "%", "Emergency Preparedness"),
  S(1, "", "First Aid Kit (Updated)"),
  S(0, "", "Expired Band-Aids"),
  S(100, "%", "Band-Aid Freshness"),
  S(1, "", "Knows CPR"),
  S(100, "%", "Life-Saving Potential"),
  S(0, "", "Emergencies Panicked Through"),
  S(100, "%", "Cool Under Fire"),
  S(1, "", "Ice in His Veins (Metaphorical)"),

  // ====== TIER 9: THE VOID STARES BACK (901-975) ======
  S(0, "", "Times He Forgot His Own Birthday"),
  S(100, "%", "Remembers YOUR Birthday"),
  S(0, "", "Wrong Birthday Dates"),
  S(100, "%", "Birthday Card Accuracy"),
  S(1, "", "Birthday Cake Slicer (Fair)"),
  S(0, "", "Uneven Cake Slices"),
  S(100, "%", "Cake Equity"),
  S(1, "", "Pro-Cake"),
  S(0, "", "Anti-Cake Sentiments"),
  S(100, "%", "Pro-Frosting"),
  S(0, "", "Scraped Off Frosting"),
  S(1, "", "Corner Piece Guy"),
  S(100, "%", "Cake Corner Passion"),
  S(0, "", "Eaten Someone Else's Slice"),
  S(100, "%", "Cake Boundary Respect"),
  S(0, "", "Double Dipped"),
  S(100, "%", "Dip Integrity"),
  S(0, "", "Chip Fragments Left in Dip"),
  S(100, "%", "Clean Break Rate"),
  S(1, "", "Chip Technique: Flawless"),
  S(0, "", "Salsa on Shirt"),
  S(100, "%", "Salsa Control"),
  S(0, "", "Guac Extra Complaints"),
  S(100, "%", "Pays for Extra Guac"),
  S(1, "", "Pro-Guac (Always)"),
  S(0, "", "Avocado Takes That Are Wrong"),
  S(100, "%", "Avocado Correctness"),
  S(1, "", "Knows When Avocado Is Ripe"),
  S(0, "", "Brown Avocados Served"),
  S(100, "%", "Produce Selection"),
  S(1, "", "Squeeze Test Expert"),
  S(0, "", "Bruised Fruit Purchased"),
  S(100, "%", "Fruit Quality"),
  S(0, "", "Banana Bread Not Made From Old Bananas"),
  S(1, "", "Actually Makes the Banana Bread"),
  S(100, "%", "Banana Follow-Through"),
  S(0, "", "Wasted Food"),
  S(100, "%", "Eats Leftovers"),
  S(1, "", "Tupperware Game: Strong"),
  S(0, "", "Missing Tupperware Lids"),
  S(100, "%", "Lid-to-Container Ratio"),
  S(1, "", "Organized Tupperware Drawer"),
  S(0, "", "Tupperware Avalanches"),
  S(100, "%", "Drawer Stability"),
  S(0, "", "Junk Drawer Chaos"),
  S(100, "%", "Every Drawer Has a Purpose"),
  S(1, "", "Drawer Philosopher"),
  S(0, "", "Existential Drawer Crises"),
  S(100, "%", "Drawer Mindfulness"),
  S(1, "", "Knows Where Everything Is"),
  S(0, "", "Lost Items"),
  S(100, "%", "Spatial Awareness"),
  S(1, "", "Has a System for Keys"),
  S(0, "", "Locked Out"),
  S(100, "%", "Key Reliability"),
  S(1, "", "Bowl by the Door"),
  S(0, "", "Keys in Weird Places"),
  S(100, "%", "Key Placement Consistency"),
  S(0, "", "Locked Keys in Car"),
  S(100, "%", "Key Consciousness"),
  S(1, "", "Spare Key Exists"),
  S(0, "", "Spare Key Lost"),
  S(100, "%", "Backup Key Integrity"),
  S(1, "", "Gives Spare Key to Trusted Person"),
  S(100, "%", "Trust Network"),
  S(0, "", "Trust Violations"),
  S(100, "%", "Trustworthy AF"),
  S(1, "", "AF = Absolutely Faithful"),
  S(0, "", "Abbreviation Confusion"),
  S(100, "%", "Communication Clarity"),
  S(1, "", "Says What He Means"),
  S(0, "", "Hidden Meanings"),
  S(100, "%", "Transparency (We Said This Already)"),
  S(1, "", "Worth Repeating"),

  // ====== TIER 10: THE FINAL FINAL (976-1000) ======
  S(1000, "", "Stats We Promised"),
  S(1000, "", "Stats We Delivered"),
  S(0, "", "Stats We Made Up"),
  S(100, "%", "Everything Here Is True"),
  S(0, "", "Lies"),
  S(100, "%", "Honesty"),
  S(0, "", "Regrets Making This Page"),
  S(1, "", "Proud of This Page"),
  S(0, "", "Plans to Remove This"),
  S(100, "%", "Commitment to the Bit"),
  S(0, "", "Quitters on This Team"),
  S(1, "", "We Went to 1000"),
  S(0, "", "People Who Read All 1000"),
  S(1, "", "You (If You're Here)"),
  S(100, "%", "Respect for You"),
  S(0, "", "Wasted Minutes (This Was Worth It)"),
  S(1, "", "Time Well Spent"),
  S(100, "%", "Entertainment Value"),
  S(0, "", "Boring Stats"),
  S(1, "", "Last Stat on Page"),
  S(0, "", "More Stats After This"),
  S(100, "%", "Done"),
  S(1, "", "Chris Pearson"),
  S(0, "", "Reasons Not to Call Him"),
  S(1, "", "Call. Him. Now."),
];

function useChaosCounter(base: number) {
  const [count, setCount] = useState(base);
  const ref = useRef<HTMLDivElement>(null);
  const isVisible = useRef(false);
  const wobble = useMemo(() => Math.max(1, Math.ceil(base * 0.3)), [base]);

  useEffect(() => {
    if (!ref.current) return;
    const observer = new IntersectionObserver(
      ([entry]) => { isVisible.current = entry.isIntersecting; },
      { threshold: 0.1 }
    );
    observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const speed = 300 + Math.random() * 1200;
    const interval = setInterval(() => {
      if (!isVisible.current) return;
      const direction = Math.random() > 0.5 ? 1 : -1;
      const delta = Math.ceil(Math.random() * wobble) * direction;
      setCount((prev) => {
        const next = prev + delta;
        if (next > base + wobble) return base + Math.ceil(Math.random() * wobble);
        if (next < Math.max(0, base - wobble)) return base;
        return next;
      });
    }, speed);
    return () => clearInterval(interval);
  }, [base, wobble]);

  return { count, ref };
}

function MiniStat({ value, suffix, prefix, label }: { value: number; suffix: string; prefix: string; label: string }) {
  const { count, ref } = useChaosCounter(value);
  return (
    <div ref={ref} className="text-center py-1">
      <span className="text-base sm:text-lg font-serif text-navy font-bold leading-none tabular-nums">
        {prefix}{count.toLocaleString()}{suffix}
      </span>
      <p className="mt-0.5 text-slate-brand text-[7px] sm:text-[9px] uppercase tracking-wider leading-tight">
        {label}
      </p>
    </div>
  );
}

export function StatsShowcase() {
  return (
    <SectionWrapper bg="white">
      <SectionHeading
        eyebrow="By the Numbers"
        title="Every. Single. Stat."
        subtitle="We ran out of room on the resume so we put them all here. All 1,000 of them."
      />

      <div className="grid grid-cols-5 sm:grid-cols-8 md:grid-cols-10 lg:grid-cols-12 xl:grid-cols-14 gap-0.5 sm:gap-1">
        {CHRIS_STATS.map((stat, i) => (
          <div
            key={`${stat.label}-${i}`}
            className="p-1 rounded-sm bg-fog/30 ring-1 ring-navy/[0.04] hover:bg-teal/5 hover:ring-teal/20 transition-colors duration-200"
          >
            <MiniStat
              value={stat.value}
              suffix={stat.suffix}
              prefix={"prefix" in stat ? (stat.prefix as string) : ""}
              label={stat.label}
            />
          </div>
        ))}
      </div>

      <p className="text-center text-slate-brand/50 text-xs mt-8">
        Yes, all {CHRIS_STATS.length} of these are real.* <br />
        <span className="text-[10px]">*Absolutely none of this should be taken seriously except for the part where you should call Chris.</span>
      </p>
    </SectionWrapper>
  );
}
